name: Update Saturn browser client files

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    name: Copy files

    steps:
      - name: Checkout saturn webpage repo
        uses: actions/checkout@v3
        with:
          path: ./saturn-page

      - name: Checkout browser client repo
        uses: actions/checkout@main
        with:
          repository: filecoin-saturn/browser-client
          path: ./browser-client

      - name: Copy all files in filecoin-saturn/browser-client/dist/ to filecoin-saturn/homepage/public
        run: |
          rsync -r ./browser-client/dist/* ./saturn-page/public/

      - name: Commit changed files to saturn homepage repo
        run: |
          cd ./saturn-page
          git add -A
          git config user.name github-actions
          git config user.email github-actions@github.com
          git diff-index --quiet HEAD || git commit -m "Replicate files from filecoin-saturn/browser-client/dist/"
          git push
